const crypto=require('crypto');
const SUPABASE_URL='https://cajerxgiwbgevfjzkkoy.supabase.co';
const SERVICE_KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;
const KIT_COMPONENT_SLUGS=['branded-bag','branded-air-fresheners','branded-microfiber-towels','referral-cards','thank-you-cards'];
function verify(raw,sig,secret){if(!sig)throw new Error('Missing stripe-signature');const parts={};sig.split(',').forEach(p=>{const [k,v]=p.split('=');parts[k]=v});if(!parts.t||!parts.v1)throw new Error('Malformed signature');if(Math.floor(Date.now()/1000)-parseInt(parts.t,10)>300)throw new Error('Timestamp too old');const expected=crypto.createHmac('sha256',secret).update(parts.t+'.'+raw,'utf8').digest('hex');const a=Buffer.from(expected),b=Buffer.from(parts.v1);if(a.length!==b.length||!crypto.timingSafeEqual(a,b))throw new Error('Signature mismatch');return JSON.parse(raw)}
function raw(req){return new Promise((resolve,reject)=>{let d='';req.on('data',c=>d+=c);req.on('end',()=>resolve(d));req.on('error',reject)})}
async function sb(path,opts={}){const r=await fetch(SUPABASE_URL+'/rest/v1/'+path,{...opts,headers:{apikey:SERVICE_KEY,Authorization:'Bearer '+SERVICE_KEY,'Content-Type':'application/json',Prefer:opts.prefer||'return=representation',...(opts.headers||{})}});const t=await r.text();let d;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw new Error('Supabase '+path+' failed '+r.status+': '+JSON.stringify(d));return d}
function shipping(s){const x=s.shipping_details||s.customer_details||{},a=x.address||{};return{shipping_name:x.name||null,shipping_address_line1:a.line1||null,shipping_address_line2:a.line2||null,shipping_city:a.city||null,shipping_state:a.state||null,shipping_postal_code:a.postal_code||null,shipping_country:a.country||'US'}}
async function supplier(slug){const rows=await sb('brandr_supplier_products?product_slug=eq.'+encodeURIComponent(slug)+'&active=eq.true&order=priority.asc&limit=1&select=supplier_id');return rows?.[0]?.supplier_id||null}
async function createItem(orderId,slug,qty){await sb('brandr_fulfillment_items',{method:'POST',body:JSON.stringify({fulfillment_order_id:orderId,product_slug:slug,supplier_id:await supplier(slug),quantity:qty,status:'queued',component_key:slug})})}
async function newOrder(payload){const rows=await sb('brandr_fulfillment_orders',{method:'POST',headers:{Prefer:'return=representation,resolution=ignore-duplicates'},body:JSON.stringify(payload)});return rows?.[0]||null}
async function oneTime(session){const md=session.metadata||{};const order=await newOrder({status:'paid',stripe_checkout_session_id:session.id,stripe_customer_id:session.customer||null,business_name:md.biz_name||session.customer_details?.name||'Unknown',business_email:md.biz_email||session.customer_details?.email||session.customer_email||'unknown@example.com',business_website:md.biz_web||null,logo_url:md.logo_url||null,review_link:md.review_link||null,quantity:parseInt(md.quantity,10)||1,notes:[md.summary,md.founding_bonus==='100_free_decals'?'FOUNDING BONUS: $100 custom decals':null,md.free_shipping==='true'?'FREE SHIPPING':null].filter(Boolean).join(' | '),...shipping(session)});if(!order)return;
  if(md.cart_items){let items=[];try{items=JSON.parse(md.cart_items)}catch{}if(Array.isArray(items)){for(const i of items){if(i?.productSlug&&parseInt(i.quantity,10)>0)await createItem(order.id,String(i.productSlug),parseInt(i.quantity,10));}if(md.founding_bonus==='100_free_decals')await createItem(order.id,'decals',1);return;}}
  const slug=md.product_slug||null,qty=parseInt(md.quantity,10)||1;if(slug)await createItem(order.id,slug,qty);if(md.founding_bonus==='100_free_decals')await createItem(order.id,'decals',1);
}
async function invoicePaid(invoice){if(!invoice.subscription)return;const r=await fetch('https://api.stripe.com/v1/subscriptions/'+invoice.subscription,{headers:{Authorization:'Bearer '+process.env.STRIPE_SECRET_KEY}});const sub=await r.json();if(sub.error)throw new Error(sub.error.message);const md=sub.metadata||{},qty=parseInt(md.quantity,10)||(sub.items?.data?.[0]?.quantity)||25,slug=md.product_slug||'monthly-customer-kits';let components=null,extras=[];try{if(md.selected_components)components=JSON.parse(md.selected_components)}catch{}try{if(md.selected_extras)extras=JSON.parse(md.selected_extras)}catch{}const order=await newOrder({status:'paid',stripe_checkout_session_id:null,stripe_invoice_id:invoice.id,stripe_subscription_id:invoice.subscription,stripe_customer_id:invoice.customer,business_name:md.biz_name||'Unknown',business_email:md.biz_email||invoice.customer_email||'unknown@example.com',business_website:md.biz_web||null,logo_url:md.logo_url||null,review_link:md.review_link||null,quantity:qty,notes:'Monthly Brandr Kit, recurring billing cycle'});if(!order)return;const slugs=slug==='monthly-customer-kits'?['branded-bag',...(Array.isArray(components)?components:KIT_COMPONENT_SLUGS.filter(s=>s!=='branded-bag')),...(Array.isArray(extras)?extras:[])]:[slug];for(const s of slugs)await createItem(order.id,s,qty)}
module.exports=async(req,res)=>{if(req.method!=='POST')return res.status(405).send('Method not allowed');const secret=process.env.STRIPE_WEBHOOK_SECRET;if(!secret||!SERVICE_KEY)return res.status(500).send('Webhook not configured');try{const event=verify(await raw(req),req.headers['stripe-signature'],secret);if(event.type==='checkout.session.completed'&&event.data.object.mode==='payment')await oneTime(event.data.object);else if(event.type==='invoice.paid')await invoicePaid(event.data.object);return res.status(200).json({received:true})}catch(e){console.error(e);return res.status(500).json({error:e.message})}};
module.exports.config={api:{bodyParser:false}};